name: Search .claude/settings.json
on:
  schedule:
    - cron: "10 15 * * *" # UTC 15:10 = JST 24:10 (00:10)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  search_claude_settingsjson:
    runs-on: ubuntu-latest
    env:
      GHSEARCH_GITHUB_TOKEN: ${{ secrets.GHSEARCH_GITHUB_TOKEN }}
      QUERY: ".claude/settings.json+in:path"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install packages
        run: uv sync --link-mode=copy --frozen
      - name: Run script
        run: |
          set -e
          mkdir -p docs/search_results
          uv run src/github_search.py \
            --log-level DEBUG \
            --query "${QUERY}" \
            --output docs/search_results/search_claude_settingsjson.atom
      - name: Create new commit
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -f docs/search_results/search_claude_settingsjson.atom

          if ! git diff --quiet --cached ; then
            git commit -m "Update search results: ${QUERY}"
            git push
          else
            echo "No changes to commit"
          fi
